version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: gptuser
      POSTGRES_PASSWORD: gptpass
      POSTGRES_DB: gptdb
    ports:
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATABASE_URL: postgres://gptuser:gptpass@db:5432/gptdb
    stdin_open: true
    tty: true
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:      